spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shop_user
    password: strong_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration

# Production logging
logging:
  level:
    com.ecommerce.shop: INFO
    org.springframework.security: WARN
